---
title: "Gov 50 Final Project"
author: "Andrew Rosenblatt"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to sports statistics. I am most interested in basketball statistics and I am not sure which specific variables I would want to examine yet. If I can find the data, I would be more interested in looking towards college basketball statistics because, for one, I am in college, but also because the NBA is far more refined in its implementation of analytics whereas college basketball still has a ways to go in terms of using basketball analytics to best gain an advantage.

## Proposal Research Question

My research question is how does a college basketball team's pace of play affect their chances of winning? In the NBA, pace of play, more specifically a faster pace of play, has become a key point of emphasis for many teams in their quest to win more games and to reach their ultimate goal of winning an NBA championship. Despite it being the same sport just at a different level, the main talking points for a winning formula in college basketball, at least in the media, are still about winning the turnover battle and out rebounding the opponent. My hypothesis is that in college basketball, the quicker a team's pace of play is, the greater their chance of winning games is. The explanatory variable in this study will be adjusted tempo, which measures a team's number of possessions per 40 minutes compared to an average team's number of possessions in the same amount of time. The outcome variable in this study is the number of games won. If my hypothesis is correct, then teams with a higher adjusted tempo would have more wins than teams with a lower adjusted tempo on average. If this is not the case and adjusted tempo has no impact or a negative impact on the number of games a team wins, then that would disprove my hypothesis. 
